name: "PHP-CS-Fixer"

on:
  push:
    branches:
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
  pull_request:

jobs:
  php-cs-fixer:
    name: "PHP-CS-Fixer"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "PHP-CS-Fixer"
        uses: "docker://oskarstark/php-cs-fixer-ga:3.26.0"
        with:
          args: --diff --dry-run
